# DiT训练配置文件
data:
  base_dir: './data/ACDC'
  image_size: 256      # 图像大小
  batch_size: 12       # 批次大小
  num_workers: 6      # 数据加载工作进程数
  scale_to_neg1_pos1: true    # 是否进行Z标准化

model:
  type: "DiT-B/2"  # 模型类型
  # 架构参数
  input_size: 32
  in_channels: 4
  learn_sigma: false
  # 训练参数
  learning_rate: 0.0001
  weight_decay: 0.1
  training_type: "naive"
  vae_model_path: "/home/zz/app/Huggingface/models/sd-vae-ft-mse"
  image_save_path: "log_images"  # 基础路径，会被自动补充完整路径
  # 流匹配参数
  denoise_timesteps: [1, 2, 4, 8, 16, 32, 128, 256]
  denoise_timesteps_target: 256
  bootstrap_every: 8
  bootstrap_dt_bias: 0
  class_dropout_prob: 1.0
  num_classes: 1
  bootstrap_cfg: false
  cfg_scale: 0.0
  bootstrap_ema: true
  eval_size: 8
  force_t: -1
  force_dt: -1

trainer:
  max_steps: 1000
  val_check_interval: 20
#  max_epochs: 20     # 最大训练轮数
  num_sanity_val_steps: 0  # 训练前验证步数
  check_val_every_n_epoch: 50  # 每多少轮进行一次验证
  limit_val_batches: 1.0    # 验证时使用的batch比例或数量
  checkpoint_every_n_epochs: 500  # 每多少轮保存一次检查点
  save_best_model: false
  save_top_k: 1       # 保存最好的k个检查点，-1表示保存所有
  use_ema: true        # 是否使用EMA
  ema_decay: 0.999     # EMA衰减率
  log_every_n_steps: 50  # 每多少步记录一次日志
  gradient_clip_val: 1.0  # 梯度裁剪值
  accumulate_grad_batches: 1  # 梯度累积步数

logging:
  project_name: 'shortcut_model'  # WandB项目名称
